// Copyright 2026 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-bundle. DO NOT EDIT.

package openapi

const (
	// DefaultOpenAPI identifies the built-in union schema. Its suffix is the
	// newest Kubernetes minor represented by the artifact; exact source
	// coverage is recorded in the bundle metadata.
	DefaultOpenAPI = "v1.36"

	// BuiltinSchemaInfo is the value printed by kustomize openapi info.
	BuiltinSchemaInfo = "{title:Kubernetes,version:" + DefaultOpenAPI + "}"
)

func hasBuiltinOpenAPIVersion(version string) bool {
	switch version {
	case "builtin":
		return true
	case "v1.21":
		return true
	case "v1.21.2":
		return true
	case "v1.22":
		return true
	case "v1.23":
		return true
	case "v1.24":
		return true
	case "v1.25":
		return true
	case "v1.26":
		return true
	case "v1.27":
		return true
	case "v1.28":
		return true
	case "v1.29":
		return true
	case "v1.30":
		return true
	case "v1.31":
		return true
	case "v1.32":
		return true
	case "v1.33":
		return true
	case "v1.34":
		return true
	case "v1.35":
		return true
	case "v1.36":
		return true
	default:
		return false
	}
}
