// Copyright 2026 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-bundle. DO NOT EDIT.

package openapi

var generatedBuiltinSourceProvenance = []builtinSourceProvenance{ //nolint:gochecknoglobals
	{kubernetesVersion: "v1.21.2", gitCommit: "092fbfbf53427de67cac1e9fa54aaa09a28371d7", sha256: "128a984dbb5a4e5ceceef9dea0db575267678d333f53ed606300a2132d2539cc", apis: []builtinProvenanceAPI{
		{apiVersion: "batch/v1", kind: "CronJob", definition: "io.k8s.api.batch.v1.CronJob"},
		{apiVersion: "discovery.k8s.io/v1", kind: "EndpointSlice", definition: "io.k8s.api.discovery.v1.EndpointSlice"},
		{apiVersion: "policy/v1", kind: "PodDisruptionBudget", definition: "io.k8s.api.policy.v1.PodDisruptionBudget"},
	}},
	{kubernetesVersion: "v1.22.0", gitCommit: "c2b5237ccd9c0f1d600d3072634ca66cefdf272f", sha256: "d6718670e062681e4dc9e2b9dadf2b311c147cfdabcac628b9018011165d8773", apis: []builtinProvenanceAPI{
		{apiVersion: "policy/v1", kind: "Eviction", definition: "io.k8s.api.policy.v1.Eviction"},
	}},
	{kubernetesVersion: "v1.23.0", gitCommit: "ab69524f795c42094a6630298ff53f3c3ebab7f4", sha256: "4a744e0c28180c3fe90256d69ebdf57d31b8579d9d5dfcdff141cd4e2d7a3b4a", apis: []builtinProvenanceAPI{
		{apiVersion: "autoscaling/v2", kind: "HorizontalPodAutoscaler", definition: "io.k8s.api.autoscaling.v2.HorizontalPodAutoscaler"},
		{apiVersion: "flowcontrol.apiserver.k8s.io/v1beta2", kind: "FlowSchema", definition: "io.k8s.api.flowcontrol.v1beta2.FlowSchema"},
		{apiVersion: "flowcontrol.apiserver.k8s.io/v1beta2", kind: "PriorityLevelConfiguration", definition: "io.k8s.api.flowcontrol.v1beta2.PriorityLevelConfiguration"},
	}},
	{kubernetesVersion: "v1.24.0", gitCommit: "4ce5a8954017644c5420bae81d72b09b735c21f0", sha256: "0d43576f2097092c8a3f203368a8edc0d605540c9757125dae116031f182e53a", apis: []builtinProvenanceAPI{
		{apiVersion: "storage.k8s.io/v1", kind: "CSIStorageCapacity", definition: "io.k8s.api.storage.v1.CSIStorageCapacity"},
	}},
	{kubernetesVersion: "v1.25.0", gitCommit: "a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", sha256: "96354682390d446dde77eb2246fe022baa89697133a8248612ca2573e4a12120", apis: []builtinProvenanceAPI{
		{apiVersion: "networking.k8s.io/v1alpha1", kind: "ClusterCIDR", definition: "io.k8s.api.networking.v1alpha1.ClusterCIDR"},
	}},
	{kubernetesVersion: "v1.26.2", gitCommit: "fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", sha256: "ef3e53add387fd5f570d58bcac9f3d58714ce8dd9398bee7b27d354583ab5b6b", apis: []builtinProvenanceAPI{
		{apiVersion: "admissionregistration.k8s.io/v1alpha1", kind: "ValidatingAdmissionPolicy", definition: "io.k8s.api.admissionregistration.v1alpha1.ValidatingAdmissionPolicy"},
		{apiVersion: "admissionregistration.k8s.io/v1alpha1", kind: "ValidatingAdmissionPolicyBinding", definition: "io.k8s.api.admissionregistration.v1alpha1.ValidatingAdmissionPolicyBinding"},
		{apiVersion: "authentication.k8s.io/v1alpha1", kind: "SelfSubjectReview", definition: "io.k8s.api.authentication.v1alpha1.SelfSubjectReview"},
	}},
	{kubernetesVersion: "v1.27.0", gitCommit: "1b4df30b3cdfeaba6024e81e559a6cd09a089d65", sha256: "09a502c5b98190a3e47604d6df835f23e7a334dfbbc3fb80729f7bb2cabf8fc4", apis: []builtinProvenanceAPI{
		{apiVersion: "authentication.k8s.io/v1beta1", kind: "SelfSubjectReview", definition: "io.k8s.api.authentication.v1beta1.SelfSubjectReview"},
		{apiVersion: "certificates.k8s.io/v1alpha1", kind: "ClusterTrustBundle", definition: "io.k8s.api.certificates.v1alpha1.ClusterTrustBundle"},
		{apiVersion: "networking.k8s.io/v1alpha1", kind: "IPAddress", definition: "io.k8s.api.networking.v1alpha1.IPAddress"},
	}},
	{kubernetesVersion: "v1.28.0", gitCommit: "855e7c48de7388eb330da0f8d9d2394ee818fb8d", sha256: "c3d62644ad31aeca618e6f640178caf39f917ba296b4919443d9838a22a10be1", apis: []builtinProvenanceAPI{
		{apiVersion: "admissionregistration.k8s.io/v1beta1", kind: "ValidatingAdmissionPolicy", definition: "io.k8s.api.admissionregistration.v1beta1.ValidatingAdmissionPolicy"},
		{apiVersion: "admissionregistration.k8s.io/v1beta1", kind: "ValidatingAdmissionPolicyBinding", definition: "io.k8s.api.admissionregistration.v1beta1.ValidatingAdmissionPolicyBinding"},
		{apiVersion: "authentication.k8s.io/v1", kind: "SelfSubjectReview", definition: "io.k8s.api.authentication.v1.SelfSubjectReview"},
	}},
	{kubernetesVersion: "v1.29.0", gitCommit: "3f7a50f38688eb332e2a1b013678c6435d539ae6", sha256: "84c20b1e2bcedce1d9d09c03e0ccb02500cd96e62e4fa54651b0e97b3a211046", apis: []builtinProvenanceAPI{
		{apiVersion: "flowcontrol.apiserver.k8s.io/v1", kind: "FlowSchema", definition: "io.k8s.api.flowcontrol.v1.FlowSchema"},
		{apiVersion: "flowcontrol.apiserver.k8s.io/v1", kind: "PriorityLevelConfiguration", definition: "io.k8s.api.flowcontrol.v1.PriorityLevelConfiguration"},
		{apiVersion: "networking.k8s.io/v1alpha1", kind: "ServiceCIDR", definition: "io.k8s.api.networking.v1alpha1.ServiceCIDR"},
	}},
	{kubernetesVersion: "v1.30.0", gitCommit: "7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a", sha256: "94ca7544416a4f27d8cb3f8a332630d41325c5edeb2408a5aefe37ba3fd6af6d", apis: []builtinProvenanceAPI{
		{apiVersion: "admissionregistration.k8s.io/v1", kind: "ValidatingAdmissionPolicy", definition: "io.k8s.api.admissionregistration.v1.ValidatingAdmissionPolicy"},
		{apiVersion: "admissionregistration.k8s.io/v1", kind: "ValidatingAdmissionPolicyBinding", definition: "io.k8s.api.admissionregistration.v1.ValidatingAdmissionPolicyBinding"},
		{apiVersion: "resource.k8s.io/v1alpha2", kind: "ResourceClaimParameters", definition: "io.k8s.api.resource.v1alpha2.ResourceClaimParameters"},
	}},
	{kubernetesVersion: "v1.31.0", gitCommit: "9edcffcde5595e8a5b1a35f88c421764e575afce", sha256: "ac357350d9d00ee233ea9a172d7c868201ff405332fec8ffe0fda25dee3e41b4", apis: []builtinProvenanceAPI{
		{apiVersion: "coordination.k8s.io/v1alpha1", kind: "LeaseCandidate", definition: "io.k8s.api.coordination.v1alpha1.LeaseCandidate"},
		{apiVersion: "networking.k8s.io/v1beta1", kind: "IPAddress", definition: "io.k8s.api.networking.v1beta1.IPAddress"},
		{apiVersion: "networking.k8s.io/v1beta1", kind: "ServiceCIDR", definition: "io.k8s.api.networking.v1beta1.ServiceCIDR"},
	}},
	{kubernetesVersion: "v1.32.0", gitCommit: "70d3cc986aa8221cd1dfb1121852688902d3bf53", sha256: "0ba99bb42a1cf0bd35959fe82965f4eec50d404221ca299e9ef79b900e15dc00", apis: []builtinProvenanceAPI{
		{apiVersion: "admissionregistration.k8s.io/v1alpha1", kind: "MutatingAdmissionPolicy", definition: "io.k8s.api.admissionregistration.v1alpha1.MutatingAdmissionPolicy"},
		{apiVersion: "admissionregistration.k8s.io/v1alpha1", kind: "MutatingAdmissionPolicyBinding", definition: "io.k8s.api.admissionregistration.v1alpha1.MutatingAdmissionPolicyBinding"},
		{apiVersion: "coordination.k8s.io/v1alpha2", kind: "LeaseCandidate", definition: "io.k8s.api.coordination.v1alpha2.LeaseCandidate"},
	}},
	{kubernetesVersion: "v1.33.0", gitCommit: "60a317eadfcb839692a68eab88b2096f4d708f4f", sha256: "2af5abf98554af1599e516f31f7f1698085e6faa12b816401f569c097b9f7ef6", apis: []builtinProvenanceAPI{
		{apiVersion: "certificates.k8s.io/v1beta1", kind: "ClusterTrustBundle", definition: "io.k8s.api.certificates.v1beta1.ClusterTrustBundle"},
		{apiVersion: "coordination.k8s.io/v1beta1", kind: "LeaseCandidate", definition: "io.k8s.api.coordination.v1beta1.LeaseCandidate"},
		{apiVersion: "networking.k8s.io/v1", kind: "IPAddress", definition: "io.k8s.api.networking.v1.IPAddress"},
	}},
	{kubernetesVersion: "v1.34.0", gitCommit: "f28b4c9efbca5c5c0af716d9f2d5702667ee8a45", sha256: "d3b0cdc2fda15c753206d25ab459dc7c12df64e2fd652b6809687471ea751c37", apis: []builtinProvenanceAPI{
		{apiVersion: "admissionregistration.k8s.io/v1beta1", kind: "MutatingAdmissionPolicy", definition: "io.k8s.api.admissionregistration.v1beta1.MutatingAdmissionPolicy"},
		{apiVersion: "admissionregistration.k8s.io/v1beta1", kind: "MutatingAdmissionPolicyBinding", definition: "io.k8s.api.admissionregistration.v1beta1.MutatingAdmissionPolicyBinding"},
		{apiVersion: "certificates.k8s.io/v1alpha1", kind: "PodCertificateRequest", definition: "io.k8s.api.certificates.v1alpha1.PodCertificateRequest"},
	}},
	{kubernetesVersion: "v1.35.0", gitCommit: "66452049f3d692768c39c797b21b793dce80314e", sha256: "483500149ee52ce5753d75f5639101d985bb4f5e902cc05b1ba7627465d62446", apis: []builtinProvenanceAPI{
		{apiVersion: "certificates.k8s.io/v1beta1", kind: "PodCertificateRequest", definition: "io.k8s.api.certificates.v1beta1.PodCertificateRequest"},
		{apiVersion: "scheduling.k8s.io/v1alpha1", kind: "Workload", definition: "io.k8s.api.scheduling.v1alpha1.Workload"},
		{apiVersion: "storagemigration.k8s.io/v1beta1", kind: "StorageVersionMigration", definition: "io.k8s.api.storagemigration.v1beta1.StorageVersionMigration"},
	}},
	{kubernetesVersion: "v1.36.0", gitCommit: "ecf6decece6a6de25a57aad9ba90b6ce580f6f78", sha256: "dcede2063da1d7ad62ecb5af8adb6d7fabd0b52385a7fa0048afb491dac90450", apis: []builtinProvenanceAPI{
		{apiVersion: "admissionregistration.k8s.io/v1", kind: "MutatingAdmissionPolicy", definition: "io.k8s.api.admissionregistration.v1.MutatingAdmissionPolicy"},
		{apiVersion: "admissionregistration.k8s.io/v1", kind: "MutatingAdmissionPolicyBinding", definition: "io.k8s.api.admissionregistration.v1.MutatingAdmissionPolicyBinding"},
		{apiVersion: "resource.k8s.io/v1alpha3", kind: "ResourcePoolStatusRequest", definition: "io.k8s.api.resource.v1alpha3.ResourcePoolStatusRequest"},
	}},
}
