// Copyright 2026 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi/internal/patchmetagen; DO NOT EDIT.

package openapi

import "sigs.k8s.io/kustomize/kyaml/yaml"

// precomputedGVKToDef indexes every resource root in the builtin schema.
// Types mapping to a definition absent from precomputedPatchDefs carry no
// strategic-merge metadata anywhere in their tree.
var precomputedGVKToDef = map[yaml.TypeMeta]string{
	{APIVersion: "admission.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "admission.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "admission.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "admission.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "admissionregistration.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "admissionregistration.k8s.io/v1", Kind: "MutatingWebhookConfiguration"}: "io.k8s.api.admissionregistration.v1.MutatingWebhookConfiguration",
	{APIVersion: "admissionregistration.k8s.io/v1", Kind: "MutatingWebhookConfigurationList"}: "io.k8s.api.admissionregistration.v1.MutatingWebhookConfigurationList",
	{APIVersion: "admissionregistration.k8s.io/v1", Kind: "ValidatingWebhookConfiguration"}: "io.k8s.api.admissionregistration.v1.ValidatingWebhookConfiguration",
	{APIVersion: "admissionregistration.k8s.io/v1", Kind: "ValidatingWebhookConfigurationList"}: "io.k8s.api.admissionregistration.v1.ValidatingWebhookConfigurationList",
	{APIVersion: "admissionregistration.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "admissionregistration.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "admissionregistration.k8s.io/v1beta1", Kind: "MutatingWebhookConfiguration"}: "io.k8s.api.admissionregistration.v1beta1.MutatingWebhookConfiguration",
	{APIVersion: "admissionregistration.k8s.io/v1beta1", Kind: "MutatingWebhookConfigurationList"}: "io.k8s.api.admissionregistration.v1beta1.MutatingWebhookConfigurationList",
	{APIVersion: "admissionregistration.k8s.io/v1beta1", Kind: "ValidatingWebhookConfiguration"}: "io.k8s.api.admissionregistration.v1beta1.ValidatingWebhookConfiguration",
	{APIVersion: "admissionregistration.k8s.io/v1beta1", Kind: "ValidatingWebhookConfigurationList"}: "io.k8s.api.admissionregistration.v1beta1.ValidatingWebhookConfigurationList",
	{APIVersion: "admissionregistration.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "apiextensions.k8s.io/v1", Kind: "CustomResourceDefinition"}: "io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition",
	{APIVersion: "apiextensions.k8s.io/v1", Kind: "CustomResourceDefinitionList"}: "io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionList",
	{APIVersion: "apiextensions.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "apiextensions.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "apiextensions.k8s.io/v1beta1", Kind: "CustomResourceDefinition"}: "io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition",
	{APIVersion: "apiextensions.k8s.io/v1beta1", Kind: "CustomResourceDefinitionList"}: "io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionList",
	{APIVersion: "apiextensions.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "apiextensions.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "apiregistration.k8s.io/v1", Kind: "APIService"}: "io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIService",
	{APIVersion: "apiregistration.k8s.io/v1", Kind: "APIServiceList"}: "io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIServiceList",
	{APIVersion: "apiregistration.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "apiregistration.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "apiregistration.k8s.io/v1beta1", Kind: "APIService"}: "io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.APIService",
	{APIVersion: "apiregistration.k8s.io/v1beta1", Kind: "APIServiceList"}: "io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.APIServiceList",
	{APIVersion: "apiregistration.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "apiregistration.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "apps/v1", Kind: "ControllerRevision"}: "io.k8s.api.apps.v1.ControllerRevision",
	{APIVersion: "apps/v1", Kind: "ControllerRevisionList"}: "io.k8s.api.apps.v1.ControllerRevisionList",
	{APIVersion: "apps/v1", Kind: "DaemonSet"}: "io.k8s.api.apps.v1.DaemonSet",
	{APIVersion: "apps/v1", Kind: "DaemonSetList"}: "io.k8s.api.apps.v1.DaemonSetList",
	{APIVersion: "apps/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "apps/v1", Kind: "Deployment"}: "io.k8s.api.apps.v1.Deployment",
	{APIVersion: "apps/v1", Kind: "DeploymentList"}: "io.k8s.api.apps.v1.DeploymentList",
	{APIVersion: "apps/v1", Kind: "ReplicaSet"}: "io.k8s.api.apps.v1.ReplicaSet",
	{APIVersion: "apps/v1", Kind: "ReplicaSetList"}: "io.k8s.api.apps.v1.ReplicaSetList",
	{APIVersion: "apps/v1", Kind: "StatefulSet"}: "io.k8s.api.apps.v1.StatefulSet",
	{APIVersion: "apps/v1", Kind: "StatefulSetList"}: "io.k8s.api.apps.v1.StatefulSetList",
	{APIVersion: "apps/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "apps/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "apps/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "apps/v1beta2", Kind: "DeleteOptions"}: "",
	{APIVersion: "apps/v1beta2", Kind: "WatchEvent"}: "",
	{APIVersion: "authentication.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "authentication.k8s.io/v1", Kind: "TokenRequest"}: "io.k8s.api.authentication.v1.TokenRequest",
	{APIVersion: "authentication.k8s.io/v1", Kind: "TokenReview"}: "io.k8s.api.authentication.v1.TokenReview",
	{APIVersion: "authentication.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "authentication.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "authentication.k8s.io/v1beta1", Kind: "TokenReview"}: "io.k8s.api.authentication.v1beta1.TokenReview",
	{APIVersion: "authentication.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "authorization.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "authorization.k8s.io/v1", Kind: "LocalSubjectAccessReview"}: "io.k8s.api.authorization.v1.LocalSubjectAccessReview",
	{APIVersion: "authorization.k8s.io/v1", Kind: "SelfSubjectAccessReview"}: "io.k8s.api.authorization.v1.SelfSubjectAccessReview",
	{APIVersion: "authorization.k8s.io/v1", Kind: "SelfSubjectRulesReview"}: "io.k8s.api.authorization.v1.SelfSubjectRulesReview",
	{APIVersion: "authorization.k8s.io/v1", Kind: "SubjectAccessReview"}: "io.k8s.api.authorization.v1.SubjectAccessReview",
	{APIVersion: "authorization.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "authorization.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "authorization.k8s.io/v1beta1", Kind: "LocalSubjectAccessReview"}: "io.k8s.api.authorization.v1beta1.LocalSubjectAccessReview",
	{APIVersion: "authorization.k8s.io/v1beta1", Kind: "SelfSubjectAccessReview"}: "io.k8s.api.authorization.v1beta1.SelfSubjectAccessReview",
	{APIVersion: "authorization.k8s.io/v1beta1", Kind: "SelfSubjectRulesReview"}: "io.k8s.api.authorization.v1beta1.SelfSubjectRulesReview",
	{APIVersion: "authorization.k8s.io/v1beta1", Kind: "SubjectAccessReview"}: "io.k8s.api.authorization.v1beta1.SubjectAccessReview",
	{APIVersion: "authorization.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "autoscaling/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "autoscaling/v1", Kind: "HorizontalPodAutoscaler"}: "io.k8s.api.autoscaling.v1.HorizontalPodAutoscaler",
	{APIVersion: "autoscaling/v1", Kind: "HorizontalPodAutoscalerList"}: "io.k8s.api.autoscaling.v1.HorizontalPodAutoscalerList",
	{APIVersion: "autoscaling/v1", Kind: "Scale"}: "io.k8s.api.autoscaling.v1.Scale",
	{APIVersion: "autoscaling/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "autoscaling/v2beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "autoscaling/v2beta1", Kind: "HorizontalPodAutoscaler"}: "io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscaler",
	{APIVersion: "autoscaling/v2beta1", Kind: "HorizontalPodAutoscalerList"}: "io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerList",
	{APIVersion: "autoscaling/v2beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "autoscaling/v2beta2", Kind: "DeleteOptions"}: "",
	{APIVersion: "autoscaling/v2beta2", Kind: "HorizontalPodAutoscaler"}: "io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscaler",
	{APIVersion: "autoscaling/v2beta2", Kind: "HorizontalPodAutoscalerList"}: "io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerList",
	{APIVersion: "autoscaling/v2beta2", Kind: "WatchEvent"}: "",
	{APIVersion: "batch/v1", Kind: "CronJob"}: "io.k8s.api.batch.v1.CronJob",
	{APIVersion: "batch/v1", Kind: "CronJobList"}: "io.k8s.api.batch.v1.CronJobList",
	{APIVersion: "batch/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "batch/v1", Kind: "Job"}: "io.k8s.api.batch.v1.Job",
	{APIVersion: "batch/v1", Kind: "JobList"}: "io.k8s.api.batch.v1.JobList",
	{APIVersion: "batch/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "batch/v1beta1", Kind: "CronJob"}: "io.k8s.api.batch.v1beta1.CronJob",
	{APIVersion: "batch/v1beta1", Kind: "CronJobList"}: "io.k8s.api.batch.v1beta1.CronJobList",
	{APIVersion: "batch/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "batch/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "certificates.k8s.io/v1", Kind: "CertificateSigningRequest"}: "io.k8s.api.certificates.v1.CertificateSigningRequest",
	{APIVersion: "certificates.k8s.io/v1", Kind: "CertificateSigningRequestList"}: "io.k8s.api.certificates.v1.CertificateSigningRequestList",
	{APIVersion: "certificates.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "certificates.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "certificates.k8s.io/v1beta1", Kind: "CertificateSigningRequest"}: "io.k8s.api.certificates.v1beta1.CertificateSigningRequest",
	{APIVersion: "certificates.k8s.io/v1beta1", Kind: "CertificateSigningRequestList"}: "io.k8s.api.certificates.v1beta1.CertificateSigningRequestList",
	{APIVersion: "certificates.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "certificates.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "coordination.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "coordination.k8s.io/v1", Kind: "Lease"}: "io.k8s.api.coordination.v1.Lease",
	{APIVersion: "coordination.k8s.io/v1", Kind: "LeaseList"}: "io.k8s.api.coordination.v1.LeaseList",
	{APIVersion: "coordination.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "coordination.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "coordination.k8s.io/v1beta1", Kind: "Lease"}: "io.k8s.api.coordination.v1beta1.Lease",
	{APIVersion: "coordination.k8s.io/v1beta1", Kind: "LeaseList"}: "io.k8s.api.coordination.v1beta1.LeaseList",
	{APIVersion: "coordination.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "discovery.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "discovery.k8s.io/v1", Kind: "EndpointSlice"}: "io.k8s.api.discovery.v1.EndpointSlice",
	{APIVersion: "discovery.k8s.io/v1", Kind: "EndpointSliceList"}: "io.k8s.api.discovery.v1.EndpointSliceList",
	{APIVersion: "discovery.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "discovery.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "discovery.k8s.io/v1beta1", Kind: "EndpointSlice"}: "io.k8s.api.discovery.v1beta1.EndpointSlice",
	{APIVersion: "discovery.k8s.io/v1beta1", Kind: "EndpointSliceList"}: "io.k8s.api.discovery.v1beta1.EndpointSliceList",
	{APIVersion: "discovery.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "events.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "events.k8s.io/v1", Kind: "Event"}: "io.k8s.api.events.v1.Event",
	{APIVersion: "events.k8s.io/v1", Kind: "EventList"}: "io.k8s.api.events.v1.EventList",
	{APIVersion: "events.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "events.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "events.k8s.io/v1beta1", Kind: "Event"}: "io.k8s.api.events.v1beta1.Event",
	{APIVersion: "events.k8s.io/v1beta1", Kind: "EventList"}: "io.k8s.api.events.v1beta1.EventList",
	{APIVersion: "events.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "extensions/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "extensions/v1beta1", Kind: "Ingress"}: "io.k8s.api.extensions.v1beta1.Ingress",
	{APIVersion: "extensions/v1beta1", Kind: "IngressList"}: "io.k8s.api.extensions.v1beta1.IngressList",
	{APIVersion: "extensions/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "flowcontrol.apiserver.k8s.io/v1alpha1", Kind: "DeleteOptions"}: "",
	{APIVersion: "flowcontrol.apiserver.k8s.io/v1alpha1", Kind: "WatchEvent"}: "",
	{APIVersion: "flowcontrol.apiserver.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "flowcontrol.apiserver.k8s.io/v1beta1", Kind: "FlowSchema"}: "io.k8s.api.flowcontrol.v1beta1.FlowSchema",
	{APIVersion: "flowcontrol.apiserver.k8s.io/v1beta1", Kind: "FlowSchemaList"}: "io.k8s.api.flowcontrol.v1beta1.FlowSchemaList",
	{APIVersion: "flowcontrol.apiserver.k8s.io/v1beta1", Kind: "PriorityLevelConfiguration"}: "io.k8s.api.flowcontrol.v1beta1.PriorityLevelConfiguration",
	{APIVersion: "flowcontrol.apiserver.k8s.io/v1beta1", Kind: "PriorityLevelConfigurationList"}: "io.k8s.api.flowcontrol.v1beta1.PriorityLevelConfigurationList",
	{APIVersion: "flowcontrol.apiserver.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "imagepolicy.k8s.io/v1alpha1", Kind: "DeleteOptions"}: "",
	{APIVersion: "imagepolicy.k8s.io/v1alpha1", Kind: "WatchEvent"}: "",
	{APIVersion: "internal.apiserver.k8s.io/v1alpha1", Kind: "DeleteOptions"}: "",
	{APIVersion: "internal.apiserver.k8s.io/v1alpha1", Kind: "WatchEvent"}: "",
	{APIVersion: "networking.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "networking.k8s.io/v1", Kind: "Ingress"}: "io.k8s.api.networking.v1.Ingress",
	{APIVersion: "networking.k8s.io/v1", Kind: "IngressClass"}: "io.k8s.api.networking.v1.IngressClass",
	{APIVersion: "networking.k8s.io/v1", Kind: "IngressClassList"}: "io.k8s.api.networking.v1.IngressClassList",
	{APIVersion: "networking.k8s.io/v1", Kind: "IngressList"}: "io.k8s.api.networking.v1.IngressList",
	{APIVersion: "networking.k8s.io/v1", Kind: "NetworkPolicy"}: "io.k8s.api.networking.v1.NetworkPolicy",
	{APIVersion: "networking.k8s.io/v1", Kind: "NetworkPolicyList"}: "io.k8s.api.networking.v1.NetworkPolicyList",
	{APIVersion: "networking.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "networking.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "networking.k8s.io/v1beta1", Kind: "Ingress"}: "io.k8s.api.networking.v1beta1.Ingress",
	{APIVersion: "networking.k8s.io/v1beta1", Kind: "IngressClass"}: "io.k8s.api.networking.v1beta1.IngressClass",
	{APIVersion: "networking.k8s.io/v1beta1", Kind: "IngressClassList"}: "io.k8s.api.networking.v1beta1.IngressClassList",
	{APIVersion: "networking.k8s.io/v1beta1", Kind: "IngressList"}: "io.k8s.api.networking.v1beta1.IngressList",
	{APIVersion: "networking.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "node.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "node.k8s.io/v1", Kind: "RuntimeClass"}: "io.k8s.api.node.v1.RuntimeClass",
	{APIVersion: "node.k8s.io/v1", Kind: "RuntimeClassList"}: "io.k8s.api.node.v1.RuntimeClassList",
	{APIVersion: "node.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "node.k8s.io/v1alpha1", Kind: "DeleteOptions"}: "",
	{APIVersion: "node.k8s.io/v1alpha1", Kind: "WatchEvent"}: "",
	{APIVersion: "node.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "node.k8s.io/v1beta1", Kind: "RuntimeClass"}: "io.k8s.api.node.v1beta1.RuntimeClass",
	{APIVersion: "node.k8s.io/v1beta1", Kind: "RuntimeClassList"}: "io.k8s.api.node.v1beta1.RuntimeClassList",
	{APIVersion: "node.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "policy/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "policy/v1", Kind: "PodDisruptionBudget"}: "io.k8s.api.policy.v1.PodDisruptionBudget",
	{APIVersion: "policy/v1", Kind: "PodDisruptionBudgetList"}: "io.k8s.api.policy.v1.PodDisruptionBudgetList",
	{APIVersion: "policy/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "policy/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "policy/v1beta1", Kind: "Eviction"}: "io.k8s.api.policy.v1beta1.Eviction",
	{APIVersion: "policy/v1beta1", Kind: "PodDisruptionBudget"}: "io.k8s.api.policy.v1beta1.PodDisruptionBudget",
	{APIVersion: "policy/v1beta1", Kind: "PodDisruptionBudgetList"}: "io.k8s.api.policy.v1beta1.PodDisruptionBudgetList",
	{APIVersion: "policy/v1beta1", Kind: "PodSecurityPolicy"}: "io.k8s.api.policy.v1beta1.PodSecurityPolicy",
	{APIVersion: "policy/v1beta1", Kind: "PodSecurityPolicyList"}: "io.k8s.api.policy.v1beta1.PodSecurityPolicyList",
	{APIVersion: "policy/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "ClusterRole"}: "io.k8s.api.rbac.v1.ClusterRole",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "ClusterRoleBinding"}: "io.k8s.api.rbac.v1.ClusterRoleBinding",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "ClusterRoleBindingList"}: "io.k8s.api.rbac.v1.ClusterRoleBindingList",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "ClusterRoleList"}: "io.k8s.api.rbac.v1.ClusterRoleList",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "Role"}: "io.k8s.api.rbac.v1.Role",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "RoleBinding"}: "io.k8s.api.rbac.v1.RoleBinding",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "RoleBindingList"}: "io.k8s.api.rbac.v1.RoleBindingList",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "RoleList"}: "io.k8s.api.rbac.v1.RoleList",
	{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "rbac.authorization.k8s.io/v1alpha1", Kind: "DeleteOptions"}: "",
	{APIVersion: "rbac.authorization.k8s.io/v1alpha1", Kind: "WatchEvent"}: "",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "ClusterRole"}: "io.k8s.api.rbac.v1beta1.ClusterRole",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "ClusterRoleBinding"}: "io.k8s.api.rbac.v1beta1.ClusterRoleBinding",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "ClusterRoleBindingList"}: "io.k8s.api.rbac.v1beta1.ClusterRoleBindingList",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "ClusterRoleList"}: "io.k8s.api.rbac.v1beta1.ClusterRoleList",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "Role"}: "io.k8s.api.rbac.v1beta1.Role",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "RoleBinding"}: "io.k8s.api.rbac.v1beta1.RoleBinding",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "RoleBindingList"}: "io.k8s.api.rbac.v1beta1.RoleBindingList",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "RoleList"}: "io.k8s.api.rbac.v1beta1.RoleList",
	{APIVersion: "rbac.authorization.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "scheduling.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "scheduling.k8s.io/v1", Kind: "PriorityClass"}: "io.k8s.api.scheduling.v1.PriorityClass",
	{APIVersion: "scheduling.k8s.io/v1", Kind: "PriorityClassList"}: "io.k8s.api.scheduling.v1.PriorityClassList",
	{APIVersion: "scheduling.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "scheduling.k8s.io/v1alpha1", Kind: "DeleteOptions"}: "",
	{APIVersion: "scheduling.k8s.io/v1alpha1", Kind: "WatchEvent"}: "",
	{APIVersion: "scheduling.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "scheduling.k8s.io/v1beta1", Kind: "PriorityClass"}: "io.k8s.api.scheduling.v1beta1.PriorityClass",
	{APIVersion: "scheduling.k8s.io/v1beta1", Kind: "PriorityClassList"}: "io.k8s.api.scheduling.v1beta1.PriorityClassList",
	{APIVersion: "scheduling.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "storage.k8s.io/v1", Kind: "CSIDriver"}: "io.k8s.api.storage.v1.CSIDriver",
	{APIVersion: "storage.k8s.io/v1", Kind: "CSIDriverList"}: "io.k8s.api.storage.v1.CSIDriverList",
	{APIVersion: "storage.k8s.io/v1", Kind: "CSINode"}: "io.k8s.api.storage.v1.CSINode",
	{APIVersion: "storage.k8s.io/v1", Kind: "CSINodeList"}: "io.k8s.api.storage.v1.CSINodeList",
	{APIVersion: "storage.k8s.io/v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "storage.k8s.io/v1", Kind: "StorageClass"}: "io.k8s.api.storage.v1.StorageClass",
	{APIVersion: "storage.k8s.io/v1", Kind: "StorageClassList"}: "io.k8s.api.storage.v1.StorageClassList",
	{APIVersion: "storage.k8s.io/v1", Kind: "VolumeAttachment"}: "io.k8s.api.storage.v1.VolumeAttachment",
	{APIVersion: "storage.k8s.io/v1", Kind: "VolumeAttachmentList"}: "io.k8s.api.storage.v1.VolumeAttachmentList",
	{APIVersion: "storage.k8s.io/v1", Kind: "WatchEvent"}: "",
	{APIVersion: "storage.k8s.io/v1alpha1", Kind: "DeleteOptions"}: "",
	{APIVersion: "storage.k8s.io/v1alpha1", Kind: "WatchEvent"}: "",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "CSIDriver"}: "io.k8s.api.storage.v1beta1.CSIDriver",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "CSIDriverList"}: "io.k8s.api.storage.v1beta1.CSIDriverList",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "CSINode"}: "io.k8s.api.storage.v1beta1.CSINode",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "CSINodeList"}: "io.k8s.api.storage.v1beta1.CSINodeList",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "CSIStorageCapacity"}: "io.k8s.api.storage.v1beta1.CSIStorageCapacity",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "CSIStorageCapacityList"}: "io.k8s.api.storage.v1beta1.CSIStorageCapacityList",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "DeleteOptions"}: "",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "StorageClass"}: "io.k8s.api.storage.v1beta1.StorageClass",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "StorageClassList"}: "io.k8s.api.storage.v1beta1.StorageClassList",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "VolumeAttachment"}: "io.k8s.api.storage.v1beta1.VolumeAttachment",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "VolumeAttachmentList"}: "io.k8s.api.storage.v1beta1.VolumeAttachmentList",
	{APIVersion: "storage.k8s.io/v1beta1", Kind: "WatchEvent"}: "",
	{APIVersion: "v1", Kind: "APIGroup"}: "",
	{APIVersion: "v1", Kind: "APIGroupList"}: "",
	{APIVersion: "v1", Kind: "APIResourceList"}: "",
	{APIVersion: "v1", Kind: "APIVersions"}: "",
	{APIVersion: "v1", Kind: "Binding"}: "io.k8s.api.core.v1.Binding",
	{APIVersion: "v1", Kind: "ComponentStatus"}: "io.k8s.api.core.v1.ComponentStatus",
	{APIVersion: "v1", Kind: "ComponentStatusList"}: "io.k8s.api.core.v1.ComponentStatusList",
	{APIVersion: "v1", Kind: "ConfigMap"}: "io.k8s.api.core.v1.ConfigMap",
	{APIVersion: "v1", Kind: "ConfigMapList"}: "io.k8s.api.core.v1.ConfigMapList",
	{APIVersion: "v1", Kind: "DeleteOptions"}: "",
	{APIVersion: "v1", Kind: "Endpoints"}: "io.k8s.api.core.v1.Endpoints",
	{APIVersion: "v1", Kind: "EndpointsList"}: "io.k8s.api.core.v1.EndpointsList",
	{APIVersion: "v1", Kind: "Event"}: "io.k8s.api.core.v1.Event",
	{APIVersion: "v1", Kind: "EventList"}: "io.k8s.api.core.v1.EventList",
	{APIVersion: "v1", Kind: "LimitRange"}: "io.k8s.api.core.v1.LimitRange",
	{APIVersion: "v1", Kind: "LimitRangeList"}: "io.k8s.api.core.v1.LimitRangeList",
	{APIVersion: "v1", Kind: "Namespace"}: "io.k8s.api.core.v1.Namespace",
	{APIVersion: "v1", Kind: "NamespaceList"}: "io.k8s.api.core.v1.NamespaceList",
	{APIVersion: "v1", Kind: "Node"}: "io.k8s.api.core.v1.Node",
	{APIVersion: "v1", Kind: "NodeList"}: "io.k8s.api.core.v1.NodeList",
	{APIVersion: "v1", Kind: "PersistentVolume"}: "io.k8s.api.core.v1.PersistentVolume",
	{APIVersion: "v1", Kind: "PersistentVolumeClaim"}: "io.k8s.api.core.v1.PersistentVolumeClaim",
	{APIVersion: "v1", Kind: "PersistentVolumeClaimList"}: "io.k8s.api.core.v1.PersistentVolumeClaimList",
	{APIVersion: "v1", Kind: "PersistentVolumeList"}: "io.k8s.api.core.v1.PersistentVolumeList",
	{APIVersion: "v1", Kind: "Pod"}: "io.k8s.api.core.v1.Pod",
	{APIVersion: "v1", Kind: "PodList"}: "io.k8s.api.core.v1.PodList",
	{APIVersion: "v1", Kind: "PodTemplate"}: "io.k8s.api.core.v1.PodTemplate",
	{APIVersion: "v1", Kind: "PodTemplateList"}: "io.k8s.api.core.v1.PodTemplateList",
	{APIVersion: "v1", Kind: "ReplicationController"}: "io.k8s.api.core.v1.ReplicationController",
	{APIVersion: "v1", Kind: "ReplicationControllerList"}: "io.k8s.api.core.v1.ReplicationControllerList",
	{APIVersion: "v1", Kind: "ResourceQuota"}: "io.k8s.api.core.v1.ResourceQuota",
	{APIVersion: "v1", Kind: "ResourceQuotaList"}: "io.k8s.api.core.v1.ResourceQuotaList",
	{APIVersion: "v1", Kind: "Secret"}: "io.k8s.api.core.v1.Secret",
	{APIVersion: "v1", Kind: "SecretList"}: "io.k8s.api.core.v1.SecretList",
	{APIVersion: "v1", Kind: "Service"}: "io.k8s.api.core.v1.Service",
	{APIVersion: "v1", Kind: "ServiceAccount"}: "io.k8s.api.core.v1.ServiceAccount",
	{APIVersion: "v1", Kind: "ServiceAccountList"}: "io.k8s.api.core.v1.ServiceAccountList",
	{APIVersion: "v1", Kind: "ServiceList"}: "io.k8s.api.core.v1.ServiceList",
	{APIVersion: "v1", Kind: "Status"}: "",
	{APIVersion: "v1", Kind: "WatchEvent"}: "",
}

var precomputedPatchDefs = map[string]map[string]pmField{
	"io.k8s.api.admissionregistration.v1.MutatingWebhook": {
		"namespaceSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"objectSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.admissionregistration.v1.MutatingWebhookConfiguration": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"webhooks": {Strategy: "merge", MergeKey: "name", ElementRef: "io.k8s.api.admissionregistration.v1.MutatingWebhook", IsArray: true},
	},
	"io.k8s.api.admissionregistration.v1.MutatingWebhookConfigurationList": {
		"items": {ElementRef: "io.k8s.api.admissionregistration.v1.MutatingWebhookConfiguration", IsArray: true},
	},
	"io.k8s.api.admissionregistration.v1.ValidatingWebhook": {
		"namespaceSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"objectSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.admissionregistration.v1.ValidatingWebhookConfiguration": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"webhooks": {Strategy: "merge", MergeKey: "name", ElementRef: "io.k8s.api.admissionregistration.v1.ValidatingWebhook", IsArray: true},
	},
	"io.k8s.api.admissionregistration.v1.ValidatingWebhookConfigurationList": {
		"items": {ElementRef: "io.k8s.api.admissionregistration.v1.ValidatingWebhookConfiguration", IsArray: true},
	},
	"io.k8s.api.admissionregistration.v1beta1.MutatingWebhook": {
		"namespaceSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"objectSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.admissionregistration.v1beta1.MutatingWebhookConfiguration": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"webhooks": {Strategy: "merge", MergeKey: "name", ElementRef: "io.k8s.api.admissionregistration.v1beta1.MutatingWebhook", IsArray: true},
	},
	"io.k8s.api.admissionregistration.v1beta1.MutatingWebhookConfigurationList": {
		"items": {ElementRef: "io.k8s.api.admissionregistration.v1beta1.MutatingWebhookConfiguration", IsArray: true},
	},
	"io.k8s.api.admissionregistration.v1beta1.ValidatingWebhook": {
		"namespaceSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"objectSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.admissionregistration.v1beta1.ValidatingWebhookConfiguration": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"webhooks": {Strategy: "merge", MergeKey: "name", ElementRef: "io.k8s.api.admissionregistration.v1beta1.ValidatingWebhook", IsArray: true},
	},
	"io.k8s.api.admissionregistration.v1beta1.ValidatingWebhookConfigurationList": {
		"items": {ElementRef: "io.k8s.api.admissionregistration.v1beta1.ValidatingWebhookConfiguration", IsArray: true},
	},
	"io.k8s.api.apps.v1.ControllerRevision": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.apps.v1.ControllerRevisionList": {
		"items": {ElementRef: "io.k8s.api.apps.v1.ControllerRevision", IsArray: true},
	},
	"io.k8s.api.apps.v1.DaemonSet": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.apps.v1.DaemonSetSpec"},
		"status": {Ref: "io.k8s.api.apps.v1.DaemonSetStatus"},
	},
	"io.k8s.api.apps.v1.DaemonSetList": {
		"items": {ElementRef: "io.k8s.api.apps.v1.DaemonSet", IsArray: true},
	},
	"io.k8s.api.apps.v1.DaemonSetSpec": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"template": {Ref: "io.k8s.api.core.v1.PodTemplateSpec"},
	},
	"io.k8s.api.apps.v1.DaemonSetStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.apps.v1.Deployment": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.apps.v1.DeploymentSpec"},
		"status": {Ref: "io.k8s.api.apps.v1.DeploymentStatus"},
	},
	"io.k8s.api.apps.v1.DeploymentList": {
		"items": {ElementRef: "io.k8s.api.apps.v1.Deployment", IsArray: true},
	},
	"io.k8s.api.apps.v1.DeploymentSpec": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"template": {Ref: "io.k8s.api.core.v1.PodTemplateSpec"},
	},
	"io.k8s.api.apps.v1.DeploymentStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.apps.v1.ReplicaSet": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.apps.v1.ReplicaSetSpec"},
		"status": {Ref: "io.k8s.api.apps.v1.ReplicaSetStatus"},
	},
	"io.k8s.api.apps.v1.ReplicaSetList": {
		"items": {ElementRef: "io.k8s.api.apps.v1.ReplicaSet", IsArray: true},
	},
	"io.k8s.api.apps.v1.ReplicaSetSpec": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"template": {Ref: "io.k8s.api.core.v1.PodTemplateSpec"},
	},
	"io.k8s.api.apps.v1.ReplicaSetStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.apps.v1.StatefulSet": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.apps.v1.StatefulSetSpec"},
		"status": {Ref: "io.k8s.api.apps.v1.StatefulSetStatus"},
	},
	"io.k8s.api.apps.v1.StatefulSetList": {
		"items": {ElementRef: "io.k8s.api.apps.v1.StatefulSet", IsArray: true},
	},
	"io.k8s.api.apps.v1.StatefulSetSpec": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"template": {Ref: "io.k8s.api.core.v1.PodTemplateSpec"},
		"volumeClaimTemplates": {ElementRef: "io.k8s.api.core.v1.PersistentVolumeClaim", IsArray: true},
	},
	"io.k8s.api.apps.v1.StatefulSetStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.authentication.v1.TokenRequest": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authentication.v1.TokenReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authentication.v1beta1.TokenReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authorization.v1.LocalSubjectAccessReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authorization.v1.SelfSubjectAccessReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authorization.v1.SelfSubjectRulesReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authorization.v1.SubjectAccessReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authorization.v1beta1.LocalSubjectAccessReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authorization.v1beta1.SelfSubjectAccessReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authorization.v1beta1.SelfSubjectRulesReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.authorization.v1beta1.SubjectAccessReview": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.autoscaling.v1.HorizontalPodAutoscaler": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.autoscaling.v1.HorizontalPodAutoscalerList": {
		"items": {ElementRef: "io.k8s.api.autoscaling.v1.HorizontalPodAutoscaler", IsArray: true},
	},
	"io.k8s.api.autoscaling.v1.Scale": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.autoscaling.v2beta1.ExternalMetricSource": {
		"metricSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.autoscaling.v2beta1.ExternalMetricStatus": {
		"metricSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscaler": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerSpec"},
		"status": {Ref: "io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerStatus"},
	},
	"io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerList": {
		"items": {ElementRef: "io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscaler", IsArray: true},
	},
	"io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerSpec": {
		"metrics": {ElementRef: "io.k8s.api.autoscaling.v2beta1.MetricSpec", IsArray: true},
	},
	"io.k8s.api.autoscaling.v2beta1.HorizontalPodAutoscalerStatus": {
		"currentMetrics": {ElementRef: "io.k8s.api.autoscaling.v2beta1.MetricStatus", IsArray: true},
	},
	"io.k8s.api.autoscaling.v2beta1.MetricSpec": {
		"external": {Ref: "io.k8s.api.autoscaling.v2beta1.ExternalMetricSource"},
		"object": {Ref: "io.k8s.api.autoscaling.v2beta1.ObjectMetricSource"},
		"pods": {Ref: "io.k8s.api.autoscaling.v2beta1.PodsMetricSource"},
	},
	"io.k8s.api.autoscaling.v2beta1.MetricStatus": {
		"external": {Ref: "io.k8s.api.autoscaling.v2beta1.ExternalMetricStatus"},
		"object": {Ref: "io.k8s.api.autoscaling.v2beta1.ObjectMetricStatus"},
		"pods": {Ref: "io.k8s.api.autoscaling.v2beta1.PodsMetricStatus"},
	},
	"io.k8s.api.autoscaling.v2beta1.ObjectMetricSource": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.autoscaling.v2beta1.ObjectMetricStatus": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.autoscaling.v2beta1.PodsMetricSource": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.autoscaling.v2beta1.PodsMetricStatus": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.autoscaling.v2beta2.ExternalMetricSource": {
		"metric": {Ref: "io.k8s.api.autoscaling.v2beta2.MetricIdentifier"},
	},
	"io.k8s.api.autoscaling.v2beta2.ExternalMetricStatus": {
		"metric": {Ref: "io.k8s.api.autoscaling.v2beta2.MetricIdentifier"},
	},
	"io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscaler": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerSpec"},
		"status": {Ref: "io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerStatus"},
	},
	"io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerList": {
		"items": {ElementRef: "io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscaler", IsArray: true},
	},
	"io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerSpec": {
		"metrics": {ElementRef: "io.k8s.api.autoscaling.v2beta2.MetricSpec", IsArray: true},
	},
	"io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerStatus": {
		"currentMetrics": {ElementRef: "io.k8s.api.autoscaling.v2beta2.MetricStatus", IsArray: true},
	},
	"io.k8s.api.autoscaling.v2beta2.MetricIdentifier": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.autoscaling.v2beta2.MetricSpec": {
		"external": {Ref: "io.k8s.api.autoscaling.v2beta2.ExternalMetricSource"},
		"object": {Ref: "io.k8s.api.autoscaling.v2beta2.ObjectMetricSource"},
		"pods": {Ref: "io.k8s.api.autoscaling.v2beta2.PodsMetricSource"},
	},
	"io.k8s.api.autoscaling.v2beta2.MetricStatus": {
		"external": {Ref: "io.k8s.api.autoscaling.v2beta2.ExternalMetricStatus"},
		"object": {Ref: "io.k8s.api.autoscaling.v2beta2.ObjectMetricStatus"},
		"pods": {Ref: "io.k8s.api.autoscaling.v2beta2.PodsMetricStatus"},
	},
	"io.k8s.api.autoscaling.v2beta2.ObjectMetricSource": {
		"metric": {Ref: "io.k8s.api.autoscaling.v2beta2.MetricIdentifier"},
	},
	"io.k8s.api.autoscaling.v2beta2.ObjectMetricStatus": {
		"metric": {Ref: "io.k8s.api.autoscaling.v2beta2.MetricIdentifier"},
	},
	"io.k8s.api.autoscaling.v2beta2.PodsMetricSource": {
		"metric": {Ref: "io.k8s.api.autoscaling.v2beta2.MetricIdentifier"},
	},
	"io.k8s.api.autoscaling.v2beta2.PodsMetricStatus": {
		"metric": {Ref: "io.k8s.api.autoscaling.v2beta2.MetricIdentifier"},
	},
	"io.k8s.api.batch.v1.CronJob": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.batch.v1.CronJobSpec"},
	},
	"io.k8s.api.batch.v1.CronJobList": {
		"items": {ElementRef: "io.k8s.api.batch.v1.CronJob", IsArray: true},
	},
	"io.k8s.api.batch.v1.CronJobSpec": {
		"jobTemplate": {Ref: "io.k8s.api.batch.v1.JobTemplateSpec"},
	},
	"io.k8s.api.batch.v1.Job": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.batch.v1.JobSpec"},
		"status": {Ref: "io.k8s.api.batch.v1.JobStatus"},
	},
	"io.k8s.api.batch.v1.JobList": {
		"items": {ElementRef: "io.k8s.api.batch.v1.Job", IsArray: true},
	},
	"io.k8s.api.batch.v1.JobSpec": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"template": {Ref: "io.k8s.api.core.v1.PodTemplateSpec"},
	},
	"io.k8s.api.batch.v1.JobStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.batch.v1.JobTemplateSpec": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.batch.v1.JobSpec"},
	},
	"io.k8s.api.batch.v1beta1.CronJob": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.batch.v1beta1.CronJobSpec"},
	},
	"io.k8s.api.batch.v1beta1.CronJobList": {
		"items": {ElementRef: "io.k8s.api.batch.v1beta1.CronJob", IsArray: true},
	},
	"io.k8s.api.batch.v1beta1.CronJobSpec": {
		"jobTemplate": {Ref: "io.k8s.api.batch.v1beta1.JobTemplateSpec"},
	},
	"io.k8s.api.batch.v1beta1.JobTemplateSpec": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.batch.v1.JobSpec"},
	},
	"io.k8s.api.certificates.v1.CertificateSigningRequest": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.certificates.v1.CertificateSigningRequestList": {
		"items": {ElementRef: "io.k8s.api.certificates.v1.CertificateSigningRequest", IsArray: true},
	},
	"io.k8s.api.certificates.v1beta1.CertificateSigningRequest": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.certificates.v1beta1.CertificateSigningRequestList": {
		"items": {ElementRef: "io.k8s.api.certificates.v1beta1.CertificateSigningRequest", IsArray: true},
	},
	"io.k8s.api.coordination.v1.Lease": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.coordination.v1.LeaseList": {
		"items": {ElementRef: "io.k8s.api.coordination.v1.Lease", IsArray: true},
	},
	"io.k8s.api.coordination.v1beta1.Lease": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.coordination.v1beta1.LeaseList": {
		"items": {ElementRef: "io.k8s.api.coordination.v1beta1.Lease", IsArray: true},
	},
	"io.k8s.api.core.v1.Affinity": {
		"podAffinity": {Ref: "io.k8s.api.core.v1.PodAffinity"},
		"podAntiAffinity": {Ref: "io.k8s.api.core.v1.PodAntiAffinity"},
	},
	"io.k8s.api.core.v1.Binding": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.ComponentStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.ComponentStatusList": {
		"items": {ElementRef: "io.k8s.api.core.v1.ComponentStatus", IsArray: true},
	},
	"io.k8s.api.core.v1.ConfigMap": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.ConfigMapList": {
		"items": {ElementRef: "io.k8s.api.core.v1.ConfigMap", IsArray: true},
	},
	"io.k8s.api.core.v1.Container": {
		"env": {Strategy: "merge", MergeKey: "name", IsArray: true},
		"ports": {Strategy: "merge", MergeKey: "containerPort", MergeKeys: []string{"containerPort", "protocol"}, IsArray: true},
		"volumeDevices": {Strategy: "merge", MergeKey: "devicePath", IsArray: true},
		"volumeMounts": {Strategy: "merge", MergeKey: "mountPath", IsArray: true},
	},
	"io.k8s.api.core.v1.Endpoints": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.EndpointsList": {
		"items": {ElementRef: "io.k8s.api.core.v1.Endpoints", IsArray: true},
	},
	"io.k8s.api.core.v1.EphemeralContainer": {
		"env": {Strategy: "merge", MergeKey: "name", IsArray: true},
		"volumeDevices": {Strategy: "merge", MergeKey: "devicePath", IsArray: true},
		"volumeMounts": {Strategy: "merge", MergeKey: "mountPath", IsArray: true},
	},
	"io.k8s.api.core.v1.EphemeralVolumeSource": {
		"volumeClaimTemplate": {Ref: "io.k8s.api.core.v1.PersistentVolumeClaimTemplate"},
	},
	"io.k8s.api.core.v1.Event": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.EventList": {
		"items": {ElementRef: "io.k8s.api.core.v1.Event", IsArray: true},
	},
	"io.k8s.api.core.v1.LimitRange": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.LimitRangeList": {
		"items": {ElementRef: "io.k8s.api.core.v1.LimitRange", IsArray: true},
	},
	"io.k8s.api.core.v1.Namespace": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"status": {Ref: "io.k8s.api.core.v1.NamespaceStatus"},
	},
	"io.k8s.api.core.v1.NamespaceList": {
		"items": {ElementRef: "io.k8s.api.core.v1.Namespace", IsArray: true},
	},
	"io.k8s.api.core.v1.NamespaceStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.core.v1.Node": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.core.v1.NodeSpec"},
		"status": {Ref: "io.k8s.api.core.v1.NodeStatus"},
	},
	"io.k8s.api.core.v1.NodeList": {
		"items": {ElementRef: "io.k8s.api.core.v1.Node", IsArray: true},
	},
	"io.k8s.api.core.v1.NodeSpec": {
		"podCIDRs": {Strategy: "merge", IsArray: true},
	},
	"io.k8s.api.core.v1.NodeStatus": {
		"addresses": {Strategy: "merge", MergeKey: "type", IsArray: true},
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.core.v1.PersistentVolume": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.PersistentVolumeClaim": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.core.v1.PersistentVolumeClaimSpec"},
		"status": {Ref: "io.k8s.api.core.v1.PersistentVolumeClaimStatus"},
	},
	"io.k8s.api.core.v1.PersistentVolumeClaimList": {
		"items": {ElementRef: "io.k8s.api.core.v1.PersistentVolumeClaim", IsArray: true},
	},
	"io.k8s.api.core.v1.PersistentVolumeClaimSpec": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.core.v1.PersistentVolumeClaimStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.core.v1.PersistentVolumeClaimTemplate": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.core.v1.PersistentVolumeClaimSpec"},
	},
	"io.k8s.api.core.v1.PersistentVolumeList": {
		"items": {ElementRef: "io.k8s.api.core.v1.PersistentVolume", IsArray: true},
	},
	"io.k8s.api.core.v1.Pod": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.core.v1.PodSpec"},
		"status": {Ref: "io.k8s.api.core.v1.PodStatus"},
	},
	"io.k8s.api.core.v1.PodAffinity": {
		"preferredDuringSchedulingIgnoredDuringExecution": {ElementRef: "io.k8s.api.core.v1.WeightedPodAffinityTerm", IsArray: true},
		"requiredDuringSchedulingIgnoredDuringExecution": {ElementRef: "io.k8s.api.core.v1.PodAffinityTerm", IsArray: true},
	},
	"io.k8s.api.core.v1.PodAffinityTerm": {
		"labelSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"namespaceSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.core.v1.PodAntiAffinity": {
		"preferredDuringSchedulingIgnoredDuringExecution": {ElementRef: "io.k8s.api.core.v1.WeightedPodAffinityTerm", IsArray: true},
		"requiredDuringSchedulingIgnoredDuringExecution": {ElementRef: "io.k8s.api.core.v1.PodAffinityTerm", IsArray: true},
	},
	"io.k8s.api.core.v1.PodList": {
		"items": {ElementRef: "io.k8s.api.core.v1.Pod", IsArray: true},
	},
	"io.k8s.api.core.v1.PodSpec": {
		"affinity": {Ref: "io.k8s.api.core.v1.Affinity"},
		"containers": {Strategy: "merge", MergeKey: "name", ElementRef: "io.k8s.api.core.v1.Container", IsArray: true},
		"ephemeralContainers": {Strategy: "merge", MergeKey: "name", ElementRef: "io.k8s.api.core.v1.EphemeralContainer", IsArray: true},
		"hostAliases": {Strategy: "merge", MergeKey: "ip", IsArray: true},
		"imagePullSecrets": {Strategy: "merge", MergeKey: "name", IsArray: true},
		"initContainers": {Strategy: "merge", MergeKey: "name", ElementRef: "io.k8s.api.core.v1.Container", IsArray: true},
		"topologySpreadConstraints": {Strategy: "merge", MergeKey: "topologyKey", MergeKeys: []string{"topologyKey", "whenUnsatisfiable"}, ElementRef: "io.k8s.api.core.v1.TopologySpreadConstraint", IsArray: true},
		"volumes": {Strategy: "merge,retainKeys", MergeKey: "name", ElementRef: "io.k8s.api.core.v1.Volume", IsArray: true},
	},
	"io.k8s.api.core.v1.PodStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
		"podIPs": {Strategy: "merge", MergeKey: "ip", IsArray: true},
	},
	"io.k8s.api.core.v1.PodTemplate": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"template": {Ref: "io.k8s.api.core.v1.PodTemplateSpec"},
	},
	"io.k8s.api.core.v1.PodTemplateList": {
		"items": {ElementRef: "io.k8s.api.core.v1.PodTemplate", IsArray: true},
	},
	"io.k8s.api.core.v1.PodTemplateSpec": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.core.v1.PodSpec"},
	},
	"io.k8s.api.core.v1.ReplicationController": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.core.v1.ReplicationControllerSpec"},
		"status": {Ref: "io.k8s.api.core.v1.ReplicationControllerStatus"},
	},
	"io.k8s.api.core.v1.ReplicationControllerList": {
		"items": {ElementRef: "io.k8s.api.core.v1.ReplicationController", IsArray: true},
	},
	"io.k8s.api.core.v1.ReplicationControllerSpec": {
		"template": {Ref: "io.k8s.api.core.v1.PodTemplateSpec"},
	},
	"io.k8s.api.core.v1.ReplicationControllerStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", IsArray: true},
	},
	"io.k8s.api.core.v1.ResourceQuota": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.ResourceQuotaList": {
		"items": {ElementRef: "io.k8s.api.core.v1.ResourceQuota", IsArray: true},
	},
	"io.k8s.api.core.v1.Secret": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.core.v1.SecretList": {
		"items": {ElementRef: "io.k8s.api.core.v1.Secret", IsArray: true},
	},
	"io.k8s.api.core.v1.Service": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.core.v1.ServiceSpec"},
		"status": {Ref: "io.k8s.api.core.v1.ServiceStatus"},
	},
	"io.k8s.api.core.v1.ServiceAccount": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"secrets": {Strategy: "merge", MergeKey: "name", IsArray: true},
	},
	"io.k8s.api.core.v1.ServiceAccountList": {
		"items": {ElementRef: "io.k8s.api.core.v1.ServiceAccount", IsArray: true},
	},
	"io.k8s.api.core.v1.ServiceList": {
		"items": {ElementRef: "io.k8s.api.core.v1.Service", IsArray: true},
	},
	"io.k8s.api.core.v1.ServiceSpec": {
		"ports": {Strategy: "merge", MergeKey: "port", MergeKeys: []string{"port", "protocol"}, IsArray: true},
	},
	"io.k8s.api.core.v1.ServiceStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", MergeKeys: []string{"type"}, IsArray: true},
	},
	"io.k8s.api.core.v1.TopologySpreadConstraint": {
		"labelSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.core.v1.Volume": {
		"ephemeral": {Ref: "io.k8s.api.core.v1.EphemeralVolumeSource"},
	},
	"io.k8s.api.core.v1.WeightedPodAffinityTerm": {
		"podAffinityTerm": {Ref: "io.k8s.api.core.v1.PodAffinityTerm"},
	},
	"io.k8s.api.discovery.v1.EndpointSlice": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.discovery.v1.EndpointSliceList": {
		"items": {ElementRef: "io.k8s.api.discovery.v1.EndpointSlice", IsArray: true},
	},
	"io.k8s.api.discovery.v1beta1.EndpointSlice": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.discovery.v1beta1.EndpointSliceList": {
		"items": {ElementRef: "io.k8s.api.discovery.v1beta1.EndpointSlice", IsArray: true},
	},
	"io.k8s.api.events.v1.Event": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.events.v1.EventList": {
		"items": {ElementRef: "io.k8s.api.events.v1.Event", IsArray: true},
	},
	"io.k8s.api.events.v1beta1.Event": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.events.v1beta1.EventList": {
		"items": {ElementRef: "io.k8s.api.events.v1beta1.Event", IsArray: true},
	},
	"io.k8s.api.extensions.v1beta1.Ingress": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.extensions.v1beta1.IngressList": {
		"items": {ElementRef: "io.k8s.api.extensions.v1beta1.Ingress", IsArray: true},
	},
	"io.k8s.api.flowcontrol.v1beta1.FlowSchema": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.flowcontrol.v1beta1.FlowSchemaList": {
		"items": {ElementRef: "io.k8s.api.flowcontrol.v1beta1.FlowSchema", IsArray: true},
	},
	"io.k8s.api.flowcontrol.v1beta1.PriorityLevelConfiguration": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.flowcontrol.v1beta1.PriorityLevelConfigurationList": {
		"items": {ElementRef: "io.k8s.api.flowcontrol.v1beta1.PriorityLevelConfiguration", IsArray: true},
	},
	"io.k8s.api.networking.v1.Ingress": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.networking.v1.IngressClass": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.networking.v1.IngressClassList": {
		"items": {ElementRef: "io.k8s.api.networking.v1.IngressClass", IsArray: true},
	},
	"io.k8s.api.networking.v1.IngressList": {
		"items": {ElementRef: "io.k8s.api.networking.v1.Ingress", IsArray: true},
	},
	"io.k8s.api.networking.v1.NetworkPolicy": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.networking.v1.NetworkPolicySpec"},
	},
	"io.k8s.api.networking.v1.NetworkPolicyEgressRule": {
		"to": {ElementRef: "io.k8s.api.networking.v1.NetworkPolicyPeer", IsArray: true},
	},
	"io.k8s.api.networking.v1.NetworkPolicyIngressRule": {
		"from": {ElementRef: "io.k8s.api.networking.v1.NetworkPolicyPeer", IsArray: true},
	},
	"io.k8s.api.networking.v1.NetworkPolicyList": {
		"items": {ElementRef: "io.k8s.api.networking.v1.NetworkPolicy", IsArray: true},
	},
	"io.k8s.api.networking.v1.NetworkPolicyPeer": {
		"namespaceSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
		"podSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.networking.v1.NetworkPolicySpec": {
		"egress": {ElementRef: "io.k8s.api.networking.v1.NetworkPolicyEgressRule", IsArray: true},
		"ingress": {ElementRef: "io.k8s.api.networking.v1.NetworkPolicyIngressRule", IsArray: true},
		"podSelector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.networking.v1beta1.Ingress": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.networking.v1beta1.IngressClass": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.networking.v1beta1.IngressClassList": {
		"items": {ElementRef: "io.k8s.api.networking.v1beta1.IngressClass", IsArray: true},
	},
	"io.k8s.api.networking.v1beta1.IngressList": {
		"items": {ElementRef: "io.k8s.api.networking.v1beta1.Ingress", IsArray: true},
	},
	"io.k8s.api.node.v1.RuntimeClass": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.node.v1.RuntimeClassList": {
		"items": {ElementRef: "io.k8s.api.node.v1.RuntimeClass", IsArray: true},
	},
	"io.k8s.api.node.v1beta1.RuntimeClass": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.node.v1beta1.RuntimeClassList": {
		"items": {ElementRef: "io.k8s.api.node.v1beta1.RuntimeClass", IsArray: true},
	},
	"io.k8s.api.policy.v1.PodDisruptionBudget": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.policy.v1.PodDisruptionBudgetSpec"},
		"status": {Ref: "io.k8s.api.policy.v1.PodDisruptionBudgetStatus"},
	},
	"io.k8s.api.policy.v1.PodDisruptionBudgetList": {
		"items": {ElementRef: "io.k8s.api.policy.v1.PodDisruptionBudget", IsArray: true},
	},
	"io.k8s.api.policy.v1.PodDisruptionBudgetSpec": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.policy.v1.PodDisruptionBudgetStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", MergeKeys: []string{"type"}, IsArray: true},
	},
	"io.k8s.api.policy.v1beta1.Eviction": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.policy.v1beta1.PodDisruptionBudget": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.policy.v1beta1.PodDisruptionBudgetSpec"},
		"status": {Ref: "io.k8s.api.policy.v1beta1.PodDisruptionBudgetStatus"},
	},
	"io.k8s.api.policy.v1beta1.PodDisruptionBudgetList": {
		"items": {ElementRef: "io.k8s.api.policy.v1beta1.PodDisruptionBudget", IsArray: true},
	},
	"io.k8s.api.policy.v1beta1.PodDisruptionBudgetSpec": {
		"selector": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.policy.v1beta1.PodDisruptionBudgetStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", MergeKeys: []string{"type"}, IsArray: true},
	},
	"io.k8s.api.policy.v1beta1.PodSecurityPolicy": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.policy.v1beta1.PodSecurityPolicyList": {
		"items": {ElementRef: "io.k8s.api.policy.v1beta1.PodSecurityPolicy", IsArray: true},
	},
	"io.k8s.api.rbac.v1.AggregationRule": {
		"clusterRoleSelectors": {ElementRef: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector", IsArray: true},
	},
	"io.k8s.api.rbac.v1.ClusterRole": {
		"aggregationRule": {Ref: "io.k8s.api.rbac.v1.AggregationRule"},
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.rbac.v1.ClusterRoleBinding": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.rbac.v1.ClusterRoleBindingList": {
		"items": {ElementRef: "io.k8s.api.rbac.v1.ClusterRoleBinding", IsArray: true},
	},
	"io.k8s.api.rbac.v1.ClusterRoleList": {
		"items": {ElementRef: "io.k8s.api.rbac.v1.ClusterRole", IsArray: true},
	},
	"io.k8s.api.rbac.v1.Role": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.rbac.v1.RoleBinding": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.rbac.v1.RoleBindingList": {
		"items": {ElementRef: "io.k8s.api.rbac.v1.RoleBinding", IsArray: true},
	},
	"io.k8s.api.rbac.v1.RoleList": {
		"items": {ElementRef: "io.k8s.api.rbac.v1.Role", IsArray: true},
	},
	"io.k8s.api.rbac.v1beta1.AggregationRule": {
		"clusterRoleSelectors": {ElementRef: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector", IsArray: true},
	},
	"io.k8s.api.rbac.v1beta1.ClusterRole": {
		"aggregationRule": {Ref: "io.k8s.api.rbac.v1beta1.AggregationRule"},
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.rbac.v1beta1.ClusterRoleBinding": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.rbac.v1beta1.ClusterRoleBindingList": {
		"items": {ElementRef: "io.k8s.api.rbac.v1beta1.ClusterRoleBinding", IsArray: true},
	},
	"io.k8s.api.rbac.v1beta1.ClusterRoleList": {
		"items": {ElementRef: "io.k8s.api.rbac.v1beta1.ClusterRole", IsArray: true},
	},
	"io.k8s.api.rbac.v1beta1.Role": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.rbac.v1beta1.RoleBinding": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.rbac.v1beta1.RoleBindingList": {
		"items": {ElementRef: "io.k8s.api.rbac.v1beta1.RoleBinding", IsArray: true},
	},
	"io.k8s.api.rbac.v1beta1.RoleList": {
		"items": {ElementRef: "io.k8s.api.rbac.v1beta1.Role", IsArray: true},
	},
	"io.k8s.api.scheduling.v1.PriorityClass": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.scheduling.v1.PriorityClassList": {
		"items": {ElementRef: "io.k8s.api.scheduling.v1.PriorityClass", IsArray: true},
	},
	"io.k8s.api.scheduling.v1beta1.PriorityClass": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.scheduling.v1beta1.PriorityClassList": {
		"items": {ElementRef: "io.k8s.api.scheduling.v1beta1.PriorityClass", IsArray: true},
	},
	"io.k8s.api.storage.v1.CSIDriver": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.storage.v1.CSIDriverList": {
		"items": {ElementRef: "io.k8s.api.storage.v1.CSIDriver", IsArray: true},
	},
	"io.k8s.api.storage.v1.CSINode": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.storage.v1.CSINodeSpec"},
	},
	"io.k8s.api.storage.v1.CSINodeList": {
		"items": {ElementRef: "io.k8s.api.storage.v1.CSINode", IsArray: true},
	},
	"io.k8s.api.storage.v1.CSINodeSpec": {
		"drivers": {Strategy: "merge", MergeKey: "name", IsArray: true},
	},
	"io.k8s.api.storage.v1.StorageClass": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.storage.v1.StorageClassList": {
		"items": {ElementRef: "io.k8s.api.storage.v1.StorageClass", IsArray: true},
	},
	"io.k8s.api.storage.v1.VolumeAttachment": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.storage.v1.VolumeAttachmentList": {
		"items": {ElementRef: "io.k8s.api.storage.v1.VolumeAttachment", IsArray: true},
	},
	"io.k8s.api.storage.v1beta1.CSIDriver": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.storage.v1beta1.CSIDriverList": {
		"items": {ElementRef: "io.k8s.api.storage.v1beta1.CSIDriver", IsArray: true},
	},
	"io.k8s.api.storage.v1beta1.CSINode": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"spec": {Ref: "io.k8s.api.storage.v1beta1.CSINodeSpec"},
	},
	"io.k8s.api.storage.v1beta1.CSINodeList": {
		"items": {ElementRef: "io.k8s.api.storage.v1beta1.CSINode", IsArray: true},
	},
	"io.k8s.api.storage.v1beta1.CSINodeSpec": {
		"drivers": {Strategy: "merge", MergeKey: "name", IsArray: true},
	},
	"io.k8s.api.storage.v1beta1.CSIStorageCapacity": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"nodeTopology": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"},
	},
	"io.k8s.api.storage.v1beta1.CSIStorageCapacityList": {
		"items": {MergeKeys: []string{"name"}, ElementRef: "io.k8s.api.storage.v1beta1.CSIStorageCapacity", IsArray: true},
	},
	"io.k8s.api.storage.v1beta1.StorageClass": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.storage.v1beta1.StorageClassList": {
		"items": {ElementRef: "io.k8s.api.storage.v1beta1.StorageClass", IsArray: true},
	},
	"io.k8s.api.storage.v1beta1.VolumeAttachment": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.api.storage.v1beta1.VolumeAttachmentList": {
		"items": {ElementRef: "io.k8s.api.storage.v1beta1.VolumeAttachment", IsArray: true},
	},
	"io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionList": {
		"items": {ElementRef: "io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition", IsArray: true},
	},
	"io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
	},
	"io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionList": {
		"items": {ElementRef: "io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition", IsArray: true},
	},
	"io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector": {
		"matchExpressions": {ElementRef: "io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement", IsArray: true},
	},
	"io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement": {
		"key": {Strategy: "merge", MergeKey: "key"},
	},
	"io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta": {
		"finalizers": {Strategy: "merge", IsArray: true},
		"ownerReferences": {Strategy: "merge", MergeKey: "uid", IsArray: true},
	},
	"io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIService": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"status": {Ref: "io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIServiceStatus"},
	},
	"io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIServiceList": {
		"items": {ElementRef: "io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIService", IsArray: true},
	},
	"io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIServiceStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", MergeKeys: []string{"type"}, IsArray: true},
	},
	"io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.APIService": {
		"metadata": {Ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"},
		"status": {Ref: "io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.APIServiceStatus"},
	},
	"io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.APIServiceList": {
		"items": {ElementRef: "io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.APIService", IsArray: true},
	},
	"io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.APIServiceStatus": {
		"conditions": {Strategy: "merge", MergeKey: "type", MergeKeys: []string{"type"}, IsArray: true},
	},
}
