# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

resources:
- ../../base
patchesStrategicMerge:
 - deployment.yaml
namePrefix: staging-
configMapGenerator:
- name: env-config
  files:
  - config.env
