version: "2"
run:
  go: "1.22"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - godot
    - godox
    - ireturn
    - maintidx
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - testifylint
    - testpackage
    - varnamelen
    - wsl
  settings:
    dupl:
      threshold: 400
    gocyclo:
      min-complexity: 30
    gomoddirectives:
      replace-local: true
    gosec:
      config:
        G306: "0644"
    lll:
      line-length: 170
    mnd:
      ignored-functions:
        - os.WriteFile
        - make
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
              - API
              - JSON
            - []
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .WrapPrefixf(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: don't use leading
      - linters:
          - staticcheck
        text: 'SA1019: kioutil.Legacy'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new-from-rev: c94b5d8f2
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
