apiVersion: v1
kind: Service
metadata:
  name: kustomize-search
spec:
  selector:
    app: kustomize-search
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: backend-port
  type: LoadBalancer
  loadBalancerIP: ""
