# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

resources:
- ../../base
patchesStrategicMerge:
- patch.yaml
- healthcheck_patch.yaml
- memorylimit_patch.yaml
namePrefix: production-
