apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: blog-1
spec:
  chart_name: blog-1
  release: blog-1
  namespace: default
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/testchart
    subpath: .
    reference: 87aad18f7d8c6a1a08f3adc8866efd33bee6aa52
  dependencies: []
  target_state: uninitialized
