// Code generated by pluginator on ConfigMapGenerator; DO NOT EDIT.
package builtin

import (
	"sigs.k8s.io/kustomize/v3/kv"
	"sigs.k8s.io/kustomize/v3/pkg/resmap"
	"sigs.k8s.io/kustomize/v3/types"
	"sigs.k8s.io/yaml"
)

type ConfigMapGeneratorPlugin struct {
	h                *resmap.PluginHelpers
	types.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	types.GeneratorOptions
	types.ConfigMapArgs
}

func (p *ConfigMapGeneratorPlugin) Config(
	h *resmap.PluginHelpers, config []byte) (err error) {
	p.GeneratorOptions = types.GeneratorOptions{}
	p.ConfigMapArgs = types.ConfigMapArgs{}
	err = yaml.Unmarshal(config, p)
	if p.ConfigMapArgs.Name == "" {
		p.ConfigMapArgs.Name = p.Name
	}
	if p.ConfigMapArgs.Namespace == "" {
		p.ConfigMapArgs.Namespace = p.Namespace
	}
	p.h = h
	return
}

func (p *ConfigMapGeneratorPlugin) Generate() (resmap.ResMap, error) {
	return p.h.ResmapFactory().FromConfigMapArgs(
		kv.NewLoader(p.h.Loader(), p.h.Validator()),
		&p.GeneratorOptions, p.ConfigMapArgs)
}

func NewConfigMapGeneratorPlugin() resmap.GeneratorPlugin {
	return &ConfigMapGeneratorPlugin{}
}
