// Copyright 2026 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestMarkdownFileSelection(t *testing.T) {
	argsBefore, fullBefore, licenseBefore := os.Args, full, licenseFile
	t.Cleanup(func() {
		os.Args, full, licenseFile = argsBefore, fullBefore, licenseBefore
	})
	source := t.TempDir()
	for _, name := range []string{"alpha.md", "beta.md", "gamma.md", "ignored.txt"} {
		if err := os.WriteFile(filepath.Join(source, name), []byte("## command\n\nShort help.\n\n### Synopsis\nLong help.\n"), 0600); err != nil {
			t.Fatal(err)
		}
	}
	for _, tc := range []struct {
		name string
		flag string
		want []string
	}{
		{name: "all markdown by default", want: []string{"Alpha", "Beta", "Gamma"}},
		{name: "selected files retain directory order", flag: "--files=gamma.md,alpha.md", want: []string{"Alpha", "Gamma"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dest := filepath.Join(t.TempDir(), "docs")
			os.Args = []string{"mdtogo", source, dest, "--license=none"}
			if tc.flag != "" {
				os.Args = append(os.Args, tc.flag)
			}
			full, licenseFile = false, ""
			main()
			got, err := os.ReadFile(filepath.Join(dest, "docs.go"))
			if err != nil {
				t.Fatal(err)
			}
			want := "\n\n// Code generated by \"mdtogo\"; DO NOT EDIT.\npackage docs\n\n"
			declarations := make([]string, 0, len(tc.want))
			for _, name := range tc.want {
				declarations = append(declarations, "var "+name+"Short=`Short help.`\nvar "+name+"Long=`Long help.`\n")
			}
			want += strings.Join(declarations, "\n")
			if string(got) != want {
				t.Fatalf("generated documentation mismatch:\ngot:\n%s\nwant:\n%s", got, want)
			}
		})
	}
}
