# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

kind: Service
apiVersion: v1
metadata:
  name: the-service
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8080
