# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

export KUSTOMIZE_ROOT ?= $(shell pwd | sed -E 's|(.*\/kustomize)/(.*)|\1|')
include $(KUSTOMIZE_ROOT)/Makefile-modules.mk

.PHONY: lint
# No file to lint for this module
lint:
	true

.PHONY: test
# No tests for this module
test:
	true

.PHONY: build
# No command to build for this module
build:
	true
