// Code generated by pluginator on ResourceGenerator; DO NOT EDIT.
// pluginator {(devel)  unknown   }

package builtins

import (
	"sigs.k8s.io/kustomize/api/resmap"
)

type ResourceGeneratorPlugin struct {
	h        *resmap.PluginHelpers
	resource string
}

func (p *ResourceGeneratorPlugin) Config(h *resmap.PluginHelpers, config []byte) (err error) {
	p.h = h
	return
}

func (p *ResourceGeneratorPlugin) Generate() (resmap.ResMap, error) {

	resourceBytes := []byte(p.resource) //idiot
	return p.h.ResmapFactory().NewResMapFromBytes(resourceBytes)
}

func NewResourceGeneratorPlugin() resmap.GeneratorPlugin {
	return &ResourceGeneratorPlugin{}
}
