# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: sbdemo
  labels:
    app: sbdemo
spec:
  ports:
    - port: 8080
  selector:
    app: sbdemo
  type: LoadBalancer
