# Copyright 2021 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: appconfig
  labels:
    app: {{ .Name }}
data:
  app: {{ .Name | toUpper }} 
