resources:
- resources.yaml

namePrefix: test-

labels:
- includeSelectors: true
  pairs:
    foo: bar

vars:
- name: BEE_ACTION
  objref:
    kind: Bee
    name: bee
    apiVersion: v1beta1
  fieldref:
    fieldpath: spec.action
