# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-http-cache
spec:
  template:
    spec:
      containers:
      - name: redis
        image: redis:5-alpine
        imagePullPolicy: Always
        # see redis.io/topics/lru-cache for other policy options.
        args: ["--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru"]
        ports:
        - name: http-cache-port
          containerPort: 6379
