# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: redis-http-cache
spec:
  clusterIP: None
  ports:
  - protocol: "TCP"
    port: 6379
    targetPort: http-cache-port
