#!/bin/bash
set -e

# Helm chart inflator

# Reads a file like this
#
#  apiVersion: kustomize.config.k8s.io/v1
#  kind: ChartInflatorExec
#  metadata:
#    name: notImportantHere
#  chartPath: path/to/a/chart
#  values: path/to/values/file
#  helmBin: abs/path/to/helmBin
#
# Example execution:
# ./plugins/kustomize.config.k8s.io/v1/ChartInflatorExec configFile.yaml



# Yaml parsing is a ridiculous thing to do in bash,
# but let's try:
function parseYaml {
  local file=$1
  while read -r line
  do
    local k=${line%:*}
    local v=${line#*:}

    [ "$k" == "chartPath" ] && chartPath=$v
    [ "$k" == "values" ] && valuesFile=$v
    [ "$k" == "helmBin" ] && helmBin=$v
  done <"$file"

  # Trim leading space
  chartPath="${chartPath#"${chartPath%%[![:space:]]*}"}"
  valuesFile="${valuesFile#"${valuesFile%%[![:space:]]*}"}"
  helmBin="${helmBin#"${helmBin%%[![:space:]]*}"}"
}

parseYaml $1

if [ -z "$helmBin" ]; then
  helmBin=/usr/local/bin/helm
fi

if [ -z "$valuesFile" ]; then
  valuesFile=$chartPath/values.yaml
fi

function doHelm {
  $helmBin $@
}


doHelm template \
    --values $valuesFile \
    $chartPath

