apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: top-level-ns

helmGlobals:
  chartHome: charts

helmCharts:
# test a contains a namespace
- name: namespace-fill
  releaseName: test-a
  namespace: chart-ns
# test b inherits the namespace from top level
- name: namespace-fill
  releaseName: test-b
