// Code generated by 'yaegi extract gopkg.in/yaml'. DO NOT EDIT.

package yamlv3

import (
	yaml "gopkg.in/yaml.v3"
	"reflect"
)

var Symbols = map[string]map[string]reflect.Value{}

func init() {
	Symbols["gopkg.in/yaml.v3"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AliasNode":         reflect.ValueOf(yaml.AliasNode),
		"DocumentNode":      reflect.ValueOf(yaml.DocumentNode),
		"DoubleQuotedStyle": reflect.ValueOf(yaml.DoubleQuotedStyle),
		"FlowStyle":         reflect.ValueOf(yaml.FlowStyle),
		"FoldedStyle":       reflect.ValueOf(yaml.FoldedStyle),
		"LiteralStyle":      reflect.ValueOf(yaml.LiteralStyle),
		"MappingNode":       reflect.ValueOf(yaml.MappingNode),
		"Marshal":           reflect.ValueOf(yaml.Marshal),
		"NewDecoder":        reflect.ValueOf(yaml.NewDecoder),
		"NewEncoder":        reflect.ValueOf(yaml.NewEncoder),
		"ScalarNode":        reflect.ValueOf(yaml.ScalarNode),
		"SequenceNode":      reflect.ValueOf(yaml.SequenceNode),
		"SingleQuotedStyle": reflect.ValueOf(yaml.SingleQuotedStyle),
		"TaggedStyle":       reflect.ValueOf(yaml.TaggedStyle),
		"Unmarshal":         reflect.ValueOf(yaml.Unmarshal),

		// type definitions
		"Decoder":     reflect.ValueOf((*yaml.Decoder)(nil)),
		"Encoder":     reflect.ValueOf((*yaml.Encoder)(nil)),
		"IsZeroer":    reflect.ValueOf((*yaml.IsZeroer)(nil)),
		"Kind":        reflect.ValueOf((*yaml.Kind)(nil)),
		"Marshaler":   reflect.ValueOf((*yaml.Marshaler)(nil)),
		"Node":        reflect.ValueOf((*yaml.Node)(nil)),
		"Style":       reflect.ValueOf((*yaml.Style)(nil)),
		"TypeError":   reflect.ValueOf((*yaml.TypeError)(nil)),
		"Unmarshaler": reflect.ValueOf((*yaml.Unmarshaler)(nil)),

		// interface wrapper definitions
		"_IsZeroer":    reflect.ValueOf((*_gopkg_in_yaml_v3_IsZeroer)(nil)),
		"_Marshaler":   reflect.ValueOf((*_gopkg_in_yaml_v3_Marshaler)(nil)),
		"_Unmarshaler": reflect.ValueOf((*_gopkg_in_yaml_v3_Unmarshaler)(nil)),
	}
}

// _gopkg_in_yaml_v3_IsZeroer is an interface wrapper for IsZeroer type
type _gopkg_in_yaml_v3_IsZeroer struct {
	WIsZero func() bool
}

func (W _gopkg_in_yaml_v3_IsZeroer) IsZero() bool { return W.WIsZero() }

// _gopkg_in_yaml_v3_Marshaler is an interface wrapper for Marshaler type
type _gopkg_in_yaml_v3_Marshaler struct {
	WMarshalYAML func() (interface{}, error)
}

func (W _gopkg_in_yaml_v3_Marshaler) MarshalYAML() (interface{}, error) { return W.WMarshalYAML() }

// _gopkg_in_yaml_v3_Unmarshaler is an interface wrapper for Unmarshaler type
type _gopkg_in_yaml_v3_Unmarshaler struct {
	WUnmarshalYAML func(value *yaml.Node) error
}

func (W _gopkg_in_yaml_v3_Unmarshaler) UnmarshalYAML(value *yaml.Node) error {
	return W.WUnmarshalYAML(value)
}
