// Code generated by "stringer -type=BuiltinPluginType"; DO NOT EDIT.

package builtinhelpers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[AnnotationsTransformer-1]
	_ = x[ResourceGenerator-2]
	_ = x[ConfigMapGenerator-3]
	_ = x[IAMPolicyGenerator-4]
	_ = x[HashTransformer-5]
	_ = x[ImageTagTransformer-6]
	_ = x[LabelTransformer-7]
	_ = x[NamespaceTransformer-8]
	_ = x[PatchJson6902Transformer-9]
	_ = x[PatchStrategicMergeTransformer-10]
	_ = x[PatchTransformer-11]
	_ = x[PrefixSuffixTransformer-12]
	_ = x[PrefixTransformer-13]
	_ = x[SuffixTransformer-14]
	_ = x[ReplicaCountTransformer-15]
	_ = x[SecretGenerator-16]
	_ = x[ValueAddTransformer-17]
	_ = x[HelmChartInflationGenerator-18]
	_ = x[ReplacementTransformer-19]
}

const _BuiltinPluginType_name = "UnknownAnnotationsTransformerResourceGeneratorConfigMapGeneratorIAMPolicyGeneratorHashTransformerImageTagTransformerLabelTransformerNamespaceTransformerPatchJson6902TransformerPatchStrategicMergeTransformerPatchTransformerPrefixSuffixTransformerPrefixTransformerSuffixTransformerReplicaCountTransformerSecretGeneratorValueAddTransformerHelmChartInflationGeneratorReplacementTransformer"

var _BuiltinPluginType_index = [...]uint16{0, 7, 29, 46, 64, 82, 97, 116, 132, 152, 176, 206, 222, 245, 262, 279, 302, 317, 336, 363, 385}

func (i BuiltinPluginType) String() string {
	if i < 0 || i >= BuiltinPluginType(len(_BuiltinPluginType_index)-1) {
		return "BuiltinPluginType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuiltinPluginType_name[_BuiltinPluginType_index[i]:_BuiltinPluginType_index[i+1]]
}
