apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: app
  name: image-name
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: $(TO_BE_REPLACE) 
      name: image-name
      referencePolicy:
        type: Source

