apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-docs-keystore
spec:
  serviceName: "redis-docs-keystore"
  template:
    spec:
      containers:
      - name: redis
        image: redis:5-alpine
        imagePullPolicy: Always
        args:
          - "--save"
          - "900"
          - "1"
          - "--save"
          - "30"
          - "100"
          - "--appendonly"
          - "yes"
        ports:
        - name: redis-docs-port
          containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-docs-keystore-data
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: redis-docs-keystore-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
