// Copyright 2020 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ./makeOpenApiInfoDotGo.sh; DO NOT EDIT.

package kubernetesapi

const Info = "{title:Kubernetes,version:v1.17.0}"
