// Copyright 2020 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ./scripts/makeOpenApiInfoDotGo.sh; DO NOT EDIT.

package kubernetesapi

import (
	"sigs.k8s.io/kustomize/kyaml/openapi/kubernetesapi/v1_30_4"
)

const Info = "{title:Kubernetes,version:v1.30.4}"

var OpenAPIMustAsset = map[string]func(string) []byte{
	"v1.30.4": v1_30_4.MustAsset,
}

const DefaultOpenAPI = "v1.30.4"
