#!/bin/bash

# Skip the config file name argument.
shift

cat <<EOF
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-configmap-test
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
data:
  username: $1
  password: $2
EOF
