apiVersion: v1
kind: Service
metadata:
  name: kustomize-search-ui
spec:
  selector:
    app: kustomize-search
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: frontend-port
  type: LoadBalancer
  loadBalancerIP: ""
